### ISSUE TITLE
Consider another name for the config file?

### ISSUE THREAD

**Issue by dominicbarnes** [makojs/cli#34]
As time goes on, I'm liking the `mako.json` filename less and less. It feels more like a JSON data file rather than a configuration file.

My vote would be for something like `.makorc`, like all the cool kids are doing.

I'm still not thrilled about adding this to the `package.json`, but I might be able to be convinced.

**Comment by dominicbarnes** [comment]
Any change made here would also affect mako-serve, since it also has it's own CLI. Another option would be to handle this directly in mako-config, which would allow it to be more easily handled by other plugins.

**Comment by darsain** [comment]
There are more and more tools that require their own config files, and it becomes honestly annoying to provide one for each and every one of them. Fortunately, all of them also support putting their configs into a property in `package.json`. Moving them all there cleaned up repos substantially, and concentrated most of the configs into one place, which is in my opinion nicer than the sea of dotfiles.

So my vote: Do it like everyone else - have your own dotfile, but also look into `package.json` for those that prefer it this way.

**Comment by dominicbarnes** [comment]
That sounds reasonable to me!
